const btn=document.querySelector('.menu-btn');const nav=document.querySelector('.mobile-nav');btn?.addEventListener('click',()=>{const open=nav.classList.toggle('open');btn.setAttribute('aria-expanded',open?'true':'false')});document.querySelectorAll('.mobile-nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));const map={beach:['Море и плаж','Плаж',['Плажна хавлия','Сенник / плажна палатка','UV облекло']],mountain:['Планина','Навън',['Топъл слой','Дъждобран','Слинг / ергономична раница']],travel:['Пътуване','Под ръка',['Резервни дрехи','Документи','Храна за път']],camping:['Къмпинг','Къмпинг',['Постелка','Лампа / фенер','Мрежа против насекоми']]};document.querySelectorAll('.scenario').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.scenario').forEach(x=>x.classList.remove('active'));b.classList.add('active');const d=map[b.dataset.scenario];document.getElementById('scenarioLabel').textContent=d[0];document.getElementById('scenarioCategory').textContent=d[1];const labels=document.querySelectorAll('.check-group')[1].querySelectorAll('label');labels.forEach((l,i)=>{const input=l.querySelector('input').outerHTML;l.innerHTML=input+' '+d[2][i]+(i===0?' <em>2 бр.</em>':'')})}))
const aiBtn=document.getElementById('aiPersonalize');
const aiModal=document.getElementById('aiModal');
aiBtn?.addEventListener('click',()=>{aiModal.classList.add('open');aiModal.setAttribute('aria-hidden','false')});
document.querySelectorAll('.store-link').forEach(b=>b.addEventListener('click',()=>{
 const m=document.getElementById('storeModal');document.getElementById('storeTitle').textContent=b.dataset.store;m.classList.add('open');m.setAttribute('aria-hidden','false');
}));
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>{const m=document.getElementById(b.dataset.close);m.classList.remove('open');m.setAttribute('aria-hidden','true')}));
document.querySelectorAll('.modal-backdrop').forEach(m=>m.addEventListener('click',e=>{if(e.target===m){m.classList.remove('open');m.setAttribute('aria-hidden','true')}}));
